### ISSUE TITLE
Use "parameter" and "argument" appropriately

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#1911]
An _argument_ is a value passed to a function. This is at function application.

A _parameter_ is a value a function expects. This is at function definition.

**Example**:
```ocaml
# let sum u = List.fold_left ( + ) 0 u;;
val sum : int list -> int = <fun>
```
> Function `sum` has ~~an argument~~ called `u`. Function `List.fold_left` is applied to three ~~parameters~~: `( + )`, `0` and `u`.

This is wrong, it should be:

> Function `sum` has __a parameter__ called `u`. Function `List.fold_left` is applied to three __arguments__: `( + )`, `0` and `u`.

This issue is about checking if the words “parameter” and “argument” are used correctly throughout the tutorials. Whenever any of those terms is used, check if it is the right one; if it is not substitute with the other. 

Documents in scope (in urgency order).
1. [x] [A Tour of Ocaml](../blob/main/data/tutorials/getting-started/1_01_a_tour_of_ocaml.md) #1929
1. [X] [Your First Ocaml Program] (../blob/main/data/tutorials/getting-started/1_02_your_first_ocaml_program.md) Not an issue
1. [x] [Values and Functions](../blob/main/data/tutorials/language/0it_00_values_functions.md) #1930 
1. [X] [Basic Data Types and Pattern Matching](../blob/main/data/tutorials/language/0it_01_basic_datatypes.md) #1931
1. [x] [Lists](../blob/main/data/tutorials/language/0it_04_lists.md) #1932
1. [X] [Mutability, Loops and Imperative Programming](../blob/main/data/tutorials/language/0it_06_imperative.md) #1933
1. [x] [Options](../blob/main/data/tutorials/language/3ds_00_options.md) #1934
1. [X] [Arrays](../blob/main/data/tutorials/language/3ds_01_arrays.md) #1935 

Do not review the following documents (deprecated, external or rewrite ongoing):
* Labelled & Optional Arguments
* Functional Programming
* If Statements and Recusions
* Modules
* Functors
* Any CS3110 or RWO ones

**Comment by PoorlyDefinedBehaviour** [comment]
Working on it

**Comment by PoorlyDefinedBehaviour** [comment]
The words parameter and argument do not appear in [Your First Ocaml Program](https://github.com/ocaml/ocaml.org/blob/main/data/tutorials/getting-started/1_02_your_first_ocaml_program.md). It can be removed from the todo list.

**Comment by sabine** [comment]
All complete
