### ISSUE TITLE
Import `ocaml.org` content

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#97]
Meta-issue to track the migration of the content from the current `ocaml.org` website.

- [ ] 99 Problems (ocaml/ood#15)
- [ ] Releases (ocaml/ood#18)
- [X] Success stories (ocaml/ood#17, ocaml/ood#20)
- [X] Books (ocaml/ood#16)
- [x] Videos
- [X] Papers (ocaml/ood#11)
- [x] Events
- [X] English Tutorials (ocaml/ood#14)
- [x] Meetings (#111)
- [X] Companies (ocaml/ood#26)
- [X] Consortium (ocaml/ood#33)
- [X] Platform tools (ocaml/ood#34)
- [x] Academia (ocaml/ood#24)
- [x] Best known methods (new content)

**Comment by tmattio** [comment]
I believe we have imported all of the data. We can open separate issues if there's anything left.
